-- Create tables in DATA schema
-- Connect as:  CONNECT data/"Data#Pwd1"@XEPDB1

CREATE TABLE patients (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(1024) NOT NULL,
  rrn VARCHAR2(1024) NOT NULL,
  rrn_hash VARCHAR2(64) NOT NULL,
  address VARCHAR2(2048) NOT NULL,
  contact VARCHAR2(512) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_patients_rrn_hash UNIQUE (rrn_hash)
);

CREATE TABLE encounters (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  visit_at TIMESTAMP NOT NULL,
  diagnosis VARCHAR2(4000),
  notes VARCHAR2(4000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_encounters_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
);

CREATE TABLE visits (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  visit_date TIMESTAMP NOT NULL,
  doctor_name VARCHAR2(100) NOT NULL,
  diagnosis CLOB NOT NULL,
  treatment CLOB NOT NULL,
  notes CLOB NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_visits_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
);

CREATE INDEX idx_visits_patient_id ON visits(patient_id);



-- Create additional DATA tables: appointments, medications, inventory, purchase_orders
-- Connect as:  CONNECT data/"Data#Pwd1"@XEPDB1

-- APPOINTMENTS
CREATE TABLE appointments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  appointment_date TIMESTAMP NOT NULL,
  doctor_name VARCHAR2(100) NOT NULL,
  reason VARCHAR2(255) NOT NULL,
  status VARCHAR2(20) DEFAULT 'Scheduled' NOT NULL,
  notes CLOB NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT ck_appointments_status CHECK (status IN ('Scheduled','Completed','Cancelled')),
  CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
);
CREATE INDEX idx_appointments_patient_id ON appointments(patient_id);
CREATE INDEX idx_appointments_status ON appointments(status);

-- MEDICATIONS
CREATE TABLE medications (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(200) NOT NULL,
  sku VARCHAR2(100) NOT NULL,
  min_stock NUMBER DEFAULT 0 NOT NULL,
  reorder_point NUMBER DEFAULT 0 NOT NULL,
  reorder_qty NUMBER DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_medications_sku UNIQUE (sku)
);

-- INVENTORY
CREATE TABLE inventory (
  medication_id NUMBER PRIMARY KEY,
  quantity NUMBER DEFAULT 0 NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_inventory_medication FOREIGN KEY (medication_id) REFERENCES medications(id) ON DELETE CASCADE
);

-- PURCHASE ORDERS
CREATE TABLE purchase_orders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medication_id NUMBER NOT NULL,
  quantity NUMBER NOT NULL,
  status VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT ck_po_status CHECK (status IN ('Pending','Ordered','Received','Cancelled')),
  CONSTRAINT fk_po_medication FOREIGN KEY (medication_id) REFERENCES medications(id) ON DELETE CASCADE
);
CREATE INDEX idx_po_medication_id ON purchase_orders(medication_id);
CREATE INDEX idx_po_status ON purchase_orders(status);


