using Oracle.ManagedDataAccess.Client;
using System.Collections.Generic;
using WpfOxyPlotGraph.Commons;
using WpfOxyPlotGraph.Models;

namespace WpfOxyPlotGraph.Repositories
{
    public class AppointmentRepository
    {
        public void EnsureTables()
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            // Create table
            using (var cmd = connection.CreateCommand())
            {
                cmd.CommandText =
@"CREATE TABLE appointments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  appointment_date TIMESTAMP NOT NULL,
  doctor_name VARCHAR2(100) NOT NULL,
  reason VARCHAR2(255) NOT NULL,
  status VARCHAR2(20) DEFAULT 'Scheduled' NOT NULL,
  notes CLOB NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT ck_appointments_status CHECK (status IN ('Scheduled','Completed','Cancelled')),
  CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
)";
                try { cmd.ExecuteNonQuery(); } catch (OracleException ex) when (ex.Number == 955) { }
            }
            // Create indexes if not exists
            using (var idx1 = connection.CreateCommand())
            {
                idx1.CommandText = "CREATE INDEX idx_appointments_patient_id ON appointments(patient_id)";
                try { idx1.ExecuteNonQuery(); } catch (OracleException ex) when (ex.Number == 955) { }
            }
            using (var idx2 = connection.CreateCommand())
            {
                idx2.CommandText = "CREATE INDEX idx_appointments_status ON appointments(status)";
                try { idx2.ExecuteNonQuery(); } catch (OracleException ex) when (ex.Number == 955) { }
            }
        }

        public IEnumerable<Appointment> GetByPatientId(int patientId)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"SELECT id, patient_id, appointment_date, doctor_name, reason, status, notes, created_at, updated_at 
                                FROM appointments WHERE patient_id=:pid
                                ORDER BY appointment_date DESC, id DESC";
            cmd.Parameters.Add(new OracleParameter("pid", patientId));
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                yield return new Appointment
                {
                    Id = reader.GetInt32(0),
                    PatientId = reader.GetInt32(1),
                    AppointmentDate = reader.GetDateTime(2),
                    DoctorName = reader.GetString(3),
                    Reason = reader.GetString(4),
                    Status = reader.GetString(5),
                    Notes = reader.IsDBNull(6) ? string.Empty : reader.GetString(6),
                    CreatedAt = reader.GetDateTime(7),
                    UpdatedAt = reader.GetDateTime(8),
                };
            }
        }

        public IEnumerable<Appointment> GetByDoctorAndDate(string doctorName, System.DateTime date)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"SELECT id, patient_id, appointment_date, doctor_name, reason, status, notes, created_at, updated_at 
                                FROM appointments 
                                WHERE doctor_name=:doc
                                  AND TRUNC(appointment_date) = TRUNC(:day)
                                ORDER BY appointment_date ASC, id ASC";
            cmd.Parameters.Add(new OracleParameter("doc", doctorName));
            cmd.Parameters.Add(new OracleParameter("day", date));
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                yield return new Appointment
                {
                    Id = reader.GetInt32(0),
                    PatientId = reader.GetInt32(1),
                    AppointmentDate = reader.GetDateTime(2),
                    DoctorName = reader.GetString(3),
                    Reason = reader.GetString(4),
                    Status = reader.GetString(5),
                    Notes = reader.IsDBNull(6) ? string.Empty : reader.GetString(6),
                    CreatedAt = reader.GetDateTime(7),
                    UpdatedAt = reader.GetDateTime(8),
                };
            }
        }

        public int Insert(Appointment appointment)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"INSERT INTO appointments (patient_id, appointment_date, doctor_name, reason, status, notes)
                                VALUES (:pid, :adate, :doc, :reason, :status, :notes)
                                RETURNING id INTO :idOut";
            cmd.Parameters.Add(new OracleParameter("pid", appointment.PatientId));
            cmd.Parameters.Add(new OracleParameter("adate", appointment.AppointmentDate));
            cmd.Parameters.Add(new OracleParameter("doc", appointment.DoctorName));
            cmd.Parameters.Add(new OracleParameter("reason", appointment.Reason));
            cmd.Parameters.Add(new OracleParameter("status", string.IsNullOrWhiteSpace(appointment.Status) ? "Scheduled" : appointment.Status));
            cmd.Parameters.Add(new OracleParameter("notes", string.IsNullOrWhiteSpace(appointment.Notes) ? (object)System.DBNull.Value : appointment.Notes));
            var idParam = new OracleParameter("idOut", OracleDbType.Int32) { Direction = System.Data.ParameterDirection.Output };
            cmd.Parameters.Add(idParam);
            cmd.ExecuteNonQuery();
            //tem.InvalidCastException: 'Unable to cast object of type 'Oracle.ManagedDataAccess.Types.OracleDecimal' to type 'System.IConvertible'.'
            //return System.Convert.ToInt32(idParam.Value);
            return ((Oracle.ManagedDataAccess.Types.OracleDecimal)idParam.Value).ToInt32();
            
        }

        public void Update(Appointment appointment)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"UPDATE appointments
                                SET appointment_date=:adate,
                                    doctor_name=:doc,
                                    reason=:reason,
                                    status=:status,
                                    notes=:notes
                                WHERE id=:id";
            cmd.Parameters.Add(new OracleParameter("adate", appointment.AppointmentDate));
            cmd.Parameters.Add(new OracleParameter("doc", appointment.DoctorName));
            cmd.Parameters.Add(new OracleParameter("reason", appointment.Reason));
            cmd.Parameters.Add(new OracleParameter("status", string.IsNullOrWhiteSpace(appointment.Status) ? "Scheduled" : appointment.Status));
            cmd.Parameters.Add(new OracleParameter("notes", string.IsNullOrWhiteSpace(appointment.Notes) ? (object)System.DBNull.Value : appointment.Notes));
            cmd.Parameters.Add(new OracleParameter("id", appointment.Id));
            cmd.ExecuteNonQuery();
        }

        public void Cancel(int appointmentId)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"UPDATE appointments SET status='Cancelled' WHERE id=:id";
            cmd.Parameters.Add(new OracleParameter("id", appointmentId));
            cmd.ExecuteNonQuery();
        }
    }
}



