using Oracle.ManagedDataAccess.Client;
using System.Collections.Generic;
using WpfOxyPlotGraph.Commons;
using WpfOxyPlotGraph.Models;

namespace WpfOxyPlotGraph.Repositories
{
    public class MedicationRepository
    {
        public void EnsureTables()
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();

            using (var cmd = connection.CreateCommand())
            {
                cmd.CommandText =
@"CREATE TABLE medications (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(200) NOT NULL,
  sku VARCHAR2(100) NOT NULL,
  min_stock NUMBER DEFAULT 0 NOT NULL,
  reorder_point NUMBER DEFAULT 0 NOT NULL,
  reorder_qty NUMBER DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_medications_sku UNIQUE (sku)
)";
                try { cmd.ExecuteNonQuery(); } catch (OracleException ex) when (ex.Number == 955) { }
            }
        }

        public IEnumerable<Medication> GetAll()
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"SELECT id, name, sku, min_stock, reorder_point, reorder_qty, created_at, updated_at FROM medications ORDER BY name ASC";
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                yield return new Medication
                {
                    Id = reader.GetInt32(0),
                    Name = reader.GetString(1),
                    Sku = reader.GetString(2),
                    MinimumStock = reader.GetInt32(3),
                    ReorderPoint = reader.GetInt32(4),
                    ReorderQuantity = reader.GetInt32(5),
                    CreatedAt = reader.GetDateTime(6),
                    UpdatedAt = reader.GetDateTime(7)
                };
            }
        }

        public Medication? GetById(int id)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"SELECT id, name, sku, min_stock, reorder_point, reorder_qty, created_at, updated_at FROM medications WHERE id=:id";
            cmd.Parameters.Add(new OracleParameter("id", id));
            using var reader = cmd.ExecuteReader();
            if (reader.Read())
            {
                return new Medication
                {
                    Id = reader.GetInt32(0),
                    Name = reader.GetString(1),
                    Sku = reader.GetString(2),
                    MinimumStock = reader.GetInt32(3),
                    ReorderPoint = reader.GetInt32(4),
                    ReorderQuantity = reader.GetInt32(5),
                    CreatedAt = reader.GetDateTime(6),
                    UpdatedAt = reader.GetDateTime(7)
                };
            }
            return null;
        }

        public int Insert(Medication medication)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"INSERT INTO medications (name, sku, min_stock, reorder_point, reorder_qty)
                                VALUES (:name, :sku, :min_stock, :reorder_point, :reorder_qty)
                                RETURNING id INTO :idOut";
            cmd.Parameters.Add(new OracleParameter("name", medication.Name));
            cmd.Parameters.Add(new OracleParameter("sku", medication.Sku));
            cmd.Parameters.Add(new OracleParameter("min_stock", medication.MinimumStock));
            cmd.Parameters.Add(new OracleParameter("reorder_point", medication.ReorderPoint));
            cmd.Parameters.Add(new OracleParameter("reorder_qty", medication.ReorderQuantity));
            var idParam = new OracleParameter("idOut", OracleDbType.Int32) { Direction = System.Data.ParameterDirection.Output };
            cmd.Parameters.Add(idParam);
            cmd.ExecuteNonQuery();
            return ((Oracle.ManagedDataAccess.Types.OracleDecimal)idParam.Value).ToInt32();
        }

        public void Update(Medication medication)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"UPDATE medications
                                SET name=:name,
                                    sku=:sku,
                                    min_stock=:min_stock,
                                    reorder_point=:reorder_point,
                                    reorder_qty=:reorder_qty,
                                    updated_at=CURRENT_TIMESTAMP
                                WHERE id=:id";
            cmd.Parameters.Add(new OracleParameter("name", medication.Name));
            cmd.Parameters.Add(new OracleParameter("sku", medication.Sku));
            cmd.Parameters.Add(new OracleParameter("min_stock", medication.MinimumStock));
            cmd.Parameters.Add(new OracleParameter("reorder_point", medication.ReorderPoint));
            cmd.Parameters.Add(new OracleParameter("reorder_qty", medication.ReorderQuantity));
            cmd.Parameters.Add(new OracleParameter("id", medication.Id));
            cmd.ExecuteNonQuery();
        }
    }
}



