using Oracle.ManagedDataAccess.Client;
using System.Collections.Generic;
using WpfOxyPlotGraph.Commons;
using WpfOxyPlotGraph.Models;

namespace WpfOxyPlotGraph.Repositories
{
    public class PatientRepository
    {
        public void EnsureTables()
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText =
@"CREATE TABLE patients (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  rrn VARCHAR2(20) NOT NULL,
  address VARCHAR2(255) NOT NULL,
  contact VARCHAR2(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_patients_rrn UNIQUE (rrn)
)";
            try
            {
                cmd.ExecuteNonQuery();
            }
            catch (OracleException ex) when (ex.Number == 955) { /* table already exists */ }
        }

        public int Insert(Patient patient)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = "INSERT INTO patients (name, rrn, address, contact) VALUES (:name, :rrn, :address, :contact) RETURNING id INTO :idOut";
            cmd.Parameters.Add(new OracleParameter("name", patient.Name));
            cmd.Parameters.Add(new OracleParameter("rrn", patient.ResidentRegistrationNumber));
            cmd.Parameters.Add(new OracleParameter("address", patient.Address));
            cmd.Parameters.Add(new OracleParameter("contact", patient.Contact));
            var idParam = new OracleParameter("idOut", OracleDbType.Int32) { Direction = System.Data.ParameterDirection.Output };
            cmd.Parameters.Add(idParam);
            //Oracle.ManagedDataAccess.Client.OracleException: 'ORA-00001: 무결성 제약 조건(SYSTEM.UQ_PATIENTS_RRN)에 위배됩니다'
            //cmd.ExecuteNonQuery();
            try
            {
                cmd.ExecuteNonQuery();
            }
            catch (OracleException ex) when (ex.Number == 1)
            {
                throw new System.Exception("A patient with the same Resident Registration Number already exists.", ex);
            }




            //InvalidCastException: 'Unable to cast object of type 'Oracle.ManagedDataAccess.Types.OracleDecimal'
            //to type 'System.IConvertible'.'
            //return System.Convert.ToInt32(idParam.Value);

            return ((Oracle.ManagedDataAccess.Types.OracleDecimal)idParam.Value).ToInt32();

        }

        public IEnumerable<Patient> GetAll()
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = "SELECT id, name, rrn, address, contact FROM patients ORDER BY id ASC";
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                yield return new Patient
                {
                    Id = reader.GetInt32(0),
                    Name = reader.GetString(1),
                    ResidentRegistrationNumber = reader.GetString(2),
                    Address = reader.GetString(3),
                    Contact = reader.GetString(4),
                };
            }
        }
    }
}

