using Oracle.ManagedDataAccess.Client;
using System.Data;
using System.Collections.Generic;
using WpfOxyPlotGraph.Commons;
using WpfOxyPlotGraph.Models;

namespace WpfOxyPlotGraph.Repositories
{
    public class PatientRepository
    {
        public void EnsureTables()
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText =
			@"CREATE TABLE patients (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  rrn VARCHAR2(20) NOT NULL,
  rrn_hash VARCHAR2(64) NOT NULL,
  address VARCHAR2(255) NOT NULL,
  contact VARCHAR2(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_patients_rrn_hash UNIQUE (rrn_hash)
)";
            try
            {
                cmd.ExecuteNonQuery();
            }
            catch (OracleException ex) when (ex.Number == 955) { /* table already exists */ }

            // Make sure columns are large enough to hold base64-encoded ciphertext
			using var alter = connection.CreateCommand();
            alter.CommandText = "ALTER TABLE patients MODIFY (name VARCHAR2(1024), rrn VARCHAR2(1024), address VARCHAR2(2048), contact VARCHAR2(512))";
            try
            {
                alter.ExecuteNonQuery();
            }
            catch (OracleException)
            {
                // ignore if not needed or insufficient privileges
            }

			// Add rrn_hash column if missing
			using (var addHash = connection.CreateCommand())
			{
				addHash.CommandText = "ALTER TABLE patients ADD (rrn_hash VARCHAR2(64))";
				try { addHash.ExecuteNonQuery(); } catch (OracleException) { }
			}

			// Backfill rrn_hash by decrypting rrn if needed
			using (var selectAll = connection.CreateCommand())
			{
				selectAll.CommandText = "SELECT id, rrn, rrn_hash FROM patients";
				try
				{
					using var reader = selectAll.ExecuteReader();
					var updates = new List<(int Id, string Hash)>();
					while (reader.Read())
					{
						var id = reader.GetInt32(0);
						var rrnValue = reader.IsDBNull(1) ? string.Empty : reader.GetString(1);
						var currentHash = reader.IsDBNull(2) ? string.Empty : reader.GetString(2);
						var rrnPlain = Crypto.DecryptStringLenient(rrnValue, "patients.rrn");
						var rrnHash = Crypto.ComputeRrnHmacHex(rrnPlain);
						if (string.IsNullOrEmpty(currentHash) || !currentHash.Equals(rrnHash, System.StringComparison.OrdinalIgnoreCase))
						{
							updates.Add((id, rrnHash));
						}
					}
					foreach (var item in updates)
					{
						using var up = connection.CreateCommand();
						up.CommandText = "UPDATE patients SET rrn_hash=:h WHERE id=:id";
						up.Parameters.Add(new OracleParameter("h", item.Hash));
						up.Parameters.Add(new OracleParameter("id", item.Id));
						try { up.ExecuteNonQuery(); } catch (OracleException) { }
					}
				}
				catch (OracleException)
				{
					// ignore if table empty or other transient issues
				}
			}

			// Ensure NOT NULL on rrn_hash (after backfill)
			using (var setNotNull = connection.CreateCommand())
			{
				setNotNull.CommandText = "ALTER TABLE patients MODIFY (rrn_hash VARCHAR2(64) NOT NULL)";
				try { setNotNull.ExecuteNonQuery(); } catch (OracleException) { }
			}

			// Drop old UNIQUE on rrn if present and add UNIQUE on rrn_hash
			using (var dropOld = connection.CreateCommand())
			{
				dropOld.CommandText = "ALTER TABLE patients DROP CONSTRAINT uq_patients_rrn";
				try { dropOld.ExecuteNonQuery(); } catch (OracleException) { }
			}
			using (var addNew = connection.CreateCommand())
			{
				addNew.CommandText = "ALTER TABLE patients ADD CONSTRAINT uq_patients_rrn_hash UNIQUE (rrn_hash)";
				try { addNew.ExecuteNonQuery(); } catch (OracleException) { }
			}
        }

        public int Insert(Patient patient)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
			cmd.CommandText = "api.patient_insert";
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.BindByName = true;

			// Encrypt sensitive fields before storing
			var rrnPlain = patient.ResidentRegistrationNumber;
			cmd.Parameters.Add(new OracleParameter("p_name", Crypto.EncryptString(patient.Name, "patients.name")));
			cmd.Parameters.Add(new OracleParameter("p_rrn", Crypto.EncryptString(rrnPlain, "patients.rrn")));
			cmd.Parameters.Add(new OracleParameter("p_rrn_hash", Crypto.ComputeRrnHmacHex(rrnPlain)));
			cmd.Parameters.Add(new OracleParameter("p_address", Crypto.EncryptString(patient.Address, "patients.address")));
			cmd.Parameters.Add(new OracleParameter("p_contact", Crypto.EncryptString(patient.Contact, "patients.contact")));
			var idParam = new OracleParameter("p_id_out", OracleDbType.Int32) { Direction = ParameterDirection.Output };
			cmd.Parameters.Add(idParam);
            //Oracle.ManagedDataAccess.Client.OracleException: 'ORA-00001: ���Ἲ ���� ����(SYSTEM.UQ_PATIENTS_RRN)�� ����˴ϴ�'
            //cmd.ExecuteNonQuery();
            try
            {
                cmd.ExecuteNonQuery();
            }
            catch (OracleException ex) when (ex.Number == 1)
            {
                throw new System.Exception("A patient with the same Resident Registration Number already exists.", ex);
            }




            //InvalidCastException: 'Unable to cast object of type 'Oracle.ManagedDataAccess.Types.OracleDecimal'
            //to type 'System.IConvertible'.'
            //return System.Convert.ToInt32(idParam.Value);

            return ((Oracle.ManagedDataAccess.Types.OracleDecimal)idParam.Value).ToInt32();

        }

        public IEnumerable<Patient> GetAll()
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
			cmd.CommandText = "api.patient_get_all";
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.BindByName = true;
			cmd.Parameters.Add("p_cursor", OracleDbType.RefCursor, ParameterDirection.Output);

			using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                yield return new Patient
                {
                    Id = reader.GetInt32(0),
                    Name = Crypto.DecryptStringLenient(reader.GetString(1), "patients.name"),
                    ResidentRegistrationNumber = Crypto.DecryptStringLenient(reader.GetString(2), "patients.rrn"),
                    Address = Crypto.DecryptStringLenient(reader.GetString(3), "patients.address"),
                    Contact = Crypto.DecryptStringLenient(reader.GetString(4), "patients.contact"),
                };
            }
        }

        public void Update(Patient patient)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
			cmd.CommandText = "api.patient_update";
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.BindByName = true;

			var rrnPlain = patient.ResidentRegistrationNumber;
			cmd.Parameters.Add(new OracleParameter("p_id", patient.Id));
			cmd.Parameters.Add(new OracleParameter("p_name", Crypto.EncryptString(patient.Name, "patients.name")));
			cmd.Parameters.Add(new OracleParameter("p_rrn", Crypto.EncryptString(rrnPlain, "patients.rrn")));
			cmd.Parameters.Add(new OracleParameter("p_rrn_hash", Crypto.ComputeRrnHmacHex(rrnPlain)));
			cmd.Parameters.Add(new OracleParameter("p_address", Crypto.EncryptString(patient.Address, "patients.address")));
			cmd.Parameters.Add(new OracleParameter("p_contact", Crypto.EncryptString(patient.Contact, "patients.contact")));
            try
            {
                cmd.ExecuteNonQuery();
            }
            catch (OracleException ex) when (ex.Number == 1)
            {
                throw new System.Exception("A patient with the same Resident Registration Number already exists.", ex);
            }
        }
    }
}

