using Oracle.ManagedDataAccess.Client;
using System;
using WpfOxyPlotGraph.Commons;
using WpfOxyPlotGraph.Models;

namespace WpfOxyPlotGraph.Repositories
{
    public class PurchaseOrderRepository
    {
        public void EnsureTables()
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using (var cmd = connection.CreateCommand())
            {
                cmd.CommandText =
@"CREATE TABLE purchase_orders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medication_id NUMBER NOT NULL,
  quantity NUMBER NOT NULL,
  status VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_po_medication FOREIGN KEY (medication_id) REFERENCES medications(id) ON DELETE CASCADE,
  CONSTRAINT ck_po_status CHECK (status IN ('Pending','Ordered','Received','Cancelled'))
)";
                try { cmd.ExecuteNonQuery(); } catch (OracleException ex) when (ex.Number == 955) { }
            }
            using (var idx = connection.CreateCommand())
            {
                idx.CommandText = "CREATE INDEX idx_po_medication_id ON purchase_orders(medication_id)";
                try { idx.ExecuteNonQuery(); } catch (OracleException ex) when (ex.Number == 955) { }
            }
        }

        public int InsertOrIncreasePending(int medicationId, int quantity)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();

            using (var find = connection.CreateCommand())
            {
                find.CommandText = @"SELECT id, quantity FROM purchase_orders WHERE medication_id=:mid AND status='Pending' ORDER BY id FETCH FIRST 1 ROWS ONLY";
                find.Parameters.Add(new OracleParameter("mid", medicationId));
                using var reader = find.ExecuteReader();
                if (reader.Read())
                {
                    var id = reader.GetInt32(0);
                    var existingQty = reader.GetInt32(1);
                    using var upd = connection.CreateCommand();
                    upd.CommandText = @"UPDATE purchase_orders SET quantity=:qty, updated_at=CURRENT_TIMESTAMP WHERE id=:id";
                    upd.Parameters.Add(new OracleParameter("qty", existingQty + quantity));
                    upd.Parameters.Add(new OracleParameter("id", id));
                    upd.ExecuteNonQuery();
                    return id;
                }
            }

            using (var ins = connection.CreateCommand())
            {
                ins.CommandText = @"INSERT INTO purchase_orders (medication_id, quantity, status)
                                    VALUES (:mid, :qty, 'Pending') RETURNING id INTO :idOut";
                ins.Parameters.Add(new OracleParameter("mid", medicationId));
                ins.Parameters.Add(new OracleParameter("qty", quantity));
                var idParam = new OracleParameter("idOut", OracleDbType.Int32) { Direction = System.Data.ParameterDirection.Output };
                ins.Parameters.Add(idParam);
                ins.ExecuteNonQuery();
                return ((Oracle.ManagedDataAccess.Types.OracleDecimal)idParam.Value).ToInt32();
            }
        }

        public void UpdateStatus(int purchaseOrderId, string status)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"UPDATE purchase_orders SET status=:status, updated_at=CURRENT_TIMESTAMP WHERE id=:id";
            cmd.Parameters.Add(new OracleParameter("status", status));
            cmd.Parameters.Add(new OracleParameter("id", purchaseOrderId));
            cmd.ExecuteNonQuery();
        }
    }
}



