using Oracle.ManagedDataAccess.Client;
using System.Collections.Generic;
using WpfOxyPlotGraph.Commons;
using WpfOxyPlotGraph.Models;

namespace WpfOxyPlotGraph.Repositories
{
    public class VisitRepository
    {
        public void EnsureTables()
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using (var cmd = connection.CreateCommand())
            {
                cmd.CommandText =
@"CREATE TABLE visits (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  visit_date TIMESTAMP NOT NULL,
  doctor_name VARCHAR2(100) NOT NULL,
  diagnosis CLOB NOT NULL,
  treatment CLOB NOT NULL,
  notes CLOB NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_visits_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
)";
                try { cmd.ExecuteNonQuery(); } catch (OracleException ex) when (ex.Number == 955) { }
            }
            using (var idx = connection.CreateCommand())
            {
                idx.CommandText = "CREATE INDEX idx_visits_patient_id ON visits(patient_id)";
                try { idx.ExecuteNonQuery(); } catch (OracleException ex) when (ex.Number == 955) { }
            }
        }

        public IEnumerable<PatientVisit> GetByPatientId(int patientId)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"SELECT id, patient_id, visit_date, doctor_name, diagnosis, treatment, notes, created_at, updated_at 
                                FROM visits WHERE patient_id=:pid ORDER BY visit_date DESC, id DESC";
            cmd.Parameters.Add(new OracleParameter("pid", patientId));
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                yield return new PatientVisit
                {
                    Id = reader.GetInt32(0),
                    PatientId = reader.GetInt32(1),
                    VisitDate = reader.GetDateTime(2),
                    DoctorName = reader.GetString(3),
                    Diagnosis = reader.GetString(4),
                    Treatment = reader.GetString(5),
                    Notes = reader.IsDBNull(6) ? string.Empty : reader.GetString(6),
                    CreatedAt = reader.GetDateTime(7),
                    UpdatedAt = reader.GetDateTime(8),
                };
            }
        }

        public int Insert(PatientVisit visit)
        {
            using var connection = DbConnectionFactory.CreateOpenConnection();
            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"INSERT INTO visits (patient_id, visit_date, doctor_name, diagnosis, treatment, notes)
                                VALUES (:pid, :vdate, :doc, :diag, :treat, :notes)
                                RETURNING id INTO :idOut";
            cmd.Parameters.Add(new OracleParameter("pid", visit.PatientId));
            cmd.Parameters.Add(new OracleParameter("vdate", visit.VisitDate));
            cmd.Parameters.Add(new OracleParameter("doc", visit.DoctorName));
            cmd.Parameters.Add(new OracleParameter("diag", visit.Diagnosis));
            cmd.Parameters.Add(new OracleParameter("treat", visit.Treatment));
            cmd.Parameters.Add(new OracleParameter("notes", string.IsNullOrWhiteSpace(visit.Notes) ? (object)System.DBNull.Value : visit.Notes));
            var idParam = new OracleParameter("idOut", OracleDbType.Int32) { Direction = System.Data.ParameterDirection.Output };
            cmd.Parameters.Add(idParam);
            cmd.ExecuteNonQuery();
            return System.Convert.ToInt32(idParam.Value);
        }
    }
}

